# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  buildVersion: 1.1.$(Build.BuildId)

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--nologo --no-restore --configuration $(buildConfiguration) -p:Version=$(buildVersion)'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'